name: Generate Pacman and Snake Animations

on:
  schedule:
    - cron: "* */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Generate Pacman graph
      - name: Generate pacman-contribution-graph.svg
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}

      - name: Debug: list files after Pacman
        run: |
          echo "==== Pacman Debug Listing ===="
          find . -type f

      - name: Move pacman graph to output directory
        run: |
          mkdir -p dist/pacman
          mv pacman-contribution-graph.svg dist/pacman/

      # Generate Snake animations
      - name: Generate GitHub Snake animations
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Debug: list files after Snake
        run: |
          echo "==== Snake Debug Listing ===="
          find . -type f

      # Deploy both Pacman and Snake to output branch
      - name: Deploy to output branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
          keep_files: true
          commit_message: "Update Pacman and Snake animations [skip ci]"
