name: Generate pacman animation

on:
  schedule: # execute every 12 hours
    - cron: "0 0 * * *"

  workflow_dispatch:

  push:
    branches:
    - main

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate pacman-contribution-graph.svg
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}

      - name: Move pacman graph to pacman directory
        run: |
          mkdir -p dist/pacman
          mv pacman-contribution-graph.svg dist/pacman/

      - name: Push pacman graph to output branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
          keep_files: true  # <- important! prevents deleting other directories
          commit_message: "Update pacman graph [skip ci]"
